<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Mapster" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.10" PrivateAssets="all" />
    <PackageVersion Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageVersion Include="MudBlazor" Version="9.7.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OData" Version="9.5.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.16.17" />
  </ItemGroup>
</Project>